from bson import ObjectId
from pydantic import BaseModel, Field
from typing_extensions import Annotated
from typing import Optional
from pydantic.functional_validators import BeforeValidator

PyObjectId = Annotated[str, BeforeValidator(str)]

class MentorLog(BaseModel):
    """
    Model representing a Mentor Log entry. This includes the user who created the log,
    associated content, and the mentor's response to a specific question.
    """
    id: Optional[PyObjectId] = Field(default_factory=PyObjectId, alias="_id")
    user_id: PyObjectId = Field(..., alias="user_id")  # Reference to the user
    content_id: PyObjectId = Field(..., alias="content_id")  # Reference to the content
    title: Optional[str] = Field(None)  # Title of the log
    context: str  # Context of the user's question
    question: str  # Question asked by the user
    response: Optional[str] = Field(None)  # Response generated by the mentor

    class Config:
        arbitrary_types_allowed = True  # Allow ObjectId as a type
        json_encoders = {ObjectId: str}  # Encode ObjectId as a string in JSON
        json_schema_extra = {
            "example": {
                "id": "60e5bba4b2a8f8c4b6e978ff",  # Example ID
                "user_id": "60e5bba4b2a8f8c4b6e978f0",  # Example User ID
                "content_id": "60e5bba4b2a8f8c4b6e978f1",  # Example Content ID
                "title": "Understanding Python Decorators",
                "context": "I need help understanding how decorators work in Python.",
                "question": "What is the best way to understand and use decorators?",
                "response": "Decorators in Python are functions that modify the behavior of other functions or methods..."
            }
        }
